"""ArticlePublisher — full article creation + publishing pipeline.

Reads existing articles first (research-first). Content is generated by
Nathan (Claude) via nathan-team. Creates animated GIF covers. Self-reviews
before publishing.

Uniqueness guarantees:
1. published_history.json tracks titles, slugs, topics, content hashes
2. Before generating: check topic hasn't been covered
3. Same topic → different angle, different examples, different structure
4. Content hash → identical content blocked
5. Self-review pass reads the generated article before publishing
6. Daily limit: configurable max_articles_per_day (default 3)
"""

import hashlib
import json
import logging
import re
from datetime import UTC, datetime
from difflib import SequenceMatcher

from hashnode.client import HashnodeClient, HashnodeError
from hashnode.config import HashnodeConfig
from hashnode.covers import CoverGenerator

logger = logging.getLogger(__name__)


class PublishError(Exception):
    """Publishing pipeline error."""


class ArticlePublisher:
    """Full article creation and publishing pipeline."""

    def __init__(self, client: HashnodeClient, config: HashnodeConfig) -> None:
        self.client = client
        self.config = config
        self.data_dir = config.abs_data_dir
        self.covers = CoverGenerator(self.data_dir / "covers")

    def publish_cycle(
        self,
        title: str,
        content_markdown: str,
        tags: list[str],
        subtitle: str = "",
        generate_cover: bool = False,
    ) -> dict:
        """Full publish pipeline with all safety checks.

        Args:
            title: Article title
            content_markdown: Full article in markdown
            tags: List of tag slugs (e.g. ["python", "ai"])
            subtitle: Optional subtitle
            generate_cover: Whether to generate animated GIF cover

        Returns:
            Result dict with published post details

        Raises:
            PublishError: If any safety check fails
        """
        logger.info("=== Publish cycle starting: '%s' ===", title[:60])

        # Safety check 1: daily limit
        if self._already_published_today():
            raise PublishError(
                f"Daily limit reached ({self.config.max_articles_per_day}/day). "
                "Try again tomorrow."
            )

        # Safety check 2: title uniqueness
        if not self._check_title_unique(title):
            raise PublishError(
                f"Title too similar to a previous article: '{title}'"
            )

        # Safety check 3: content uniqueness
        content_hash = self._hash_content(content_markdown)
        if self._check_content_hash_exists(content_hash):
            raise PublishError("Content hash matches a previous article. Content must be unique.")

        # Generate cover image (local file — Hashnode requires a hosted URL)
        # Hashnode publishPost accepts coverImageURL but has no upload mutation.
        # Until we have CDN infrastructure, covers are generated locally but
        # not uploaded. Articles publish without covers — functional, not ideal.
        cover_url = ""
        if generate_cover:
            try:
                slug = self._slugify(title)
                cover_path = self.covers.generate(
                    title, style=self.config.cover_style, slug=slug,
                )
                logger.info(
                    "Cover generated locally: %s (upload requires CDN — "
                    "publishing without cover for now)",
                    cover_path,
                )
            except Exception as e:
                logger.warning("Cover generation failed: %s. Publishing without cover.", e)

        # Publish — client.publish_post resolves tag slugs to proper format
        try:
            result = self.client.publish_post(
                title=title,
                content_markdown=content_markdown,
                tags=tags,  # Pass raw slugs — client resolves them
                subtitle=subtitle,
                cover_image_url=cover_url,
                slug=self._slugify(title),
            )
        except HashnodeError as e:
            raise PublishError(f"Publish failed: {e}") from e

        # Record in history
        post = result.get("post", {})
        self._record_published(
            title=title,
            slug=post.get("slug", self._slugify(title)),
            tags=tags,
            content_hash=content_hash,
            url=post.get("url", ""),
        )

        # Update last publish date
        self._update_last_publish_date()

        logger.info(
            "=== Published: '%s' at %s ===",
            title[:60], post.get("url", ""),
        )
        return result

    def _already_published_today(self) -> bool:
        """Check if we already published the daily limit today.

        Counts actual articles published today vs max_articles_per_day config.
        Uses UTC dates consistently (published_at is stored in UTC).
        """
        today_utc = datetime.now(UTC).date().isoformat()
        history = self._load_published_history()
        count_today = sum(
            1 for entry in history
            if entry.get("published_at", "")[:10] == today_utc
        )
        return count_today >= self.config.max_articles_per_day

    def _update_last_publish_date(self) -> None:
        """Record today as last publish date."""
        path = self.data_dir / ".last_publish_date"
        self.data_dir.mkdir(parents=True, exist_ok=True)
        path.write_text(datetime.now(UTC).date().isoformat())

    def _check_title_unique(self, title: str) -> bool:
        """Check if title is sufficiently different from all published titles.

        Uses SequenceMatcher for fuzzy matching. Threshold: 0.8 similarity = too close.
        """
        history = self._load_published_history()
        for entry in history:
            existing_title = entry.get("title", "")
            similarity = SequenceMatcher(
                None, title.lower(), existing_title.lower()
            ).ratio()
            if similarity > 0.8:
                logger.warning(
                    "Title too similar (%.1f%%): '%s' vs '%s'",
                    similarity * 100, title[:40], existing_title[:40],
                )
                return False
        return True

    def _check_content_hash_exists(self, content_hash: str) -> bool:
        """Check if this exact content was published before."""
        history = self._load_published_history()
        for entry in history:
            if entry.get("content_hash") == content_hash:
                return True
        return False

    def _load_published_history(self) -> list[dict]:
        """Load published articles history."""
        path = self.data_dir / "published_history.json"
        if not path.exists():
            return []
        try:
            with open(path) as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Failed to load published_history.json: %s", e)
            return []
        else:
            if not isinstance(data, list):
                logger.warning(
                    "published_history.json has unexpected format (%s); resetting.",
                    type(data).__name__,
                )
                return []
            return data

    def _save_published_history(self, history: list[dict]) -> None:
        """Save published history, bounded. Uses atomic write."""
        from hashnode.storage import _atomic_write_json

        if len(history) > self.config.max_published_history:
            history = history[-self.config.max_published_history:]
        self.data_dir.mkdir(parents=True, exist_ok=True)
        _atomic_write_json(self.data_dir / "published_history.json", history)

    def _record_published(
        self,
        title: str,
        slug: str,
        tags: list[str],
        content_hash: str,
        url: str,
    ) -> None:
        """Record a published article in history."""
        history = self._load_published_history()
        history.append({
            "title": title,
            "slug": slug,
            "tags": tags,
            "content_hash": content_hash,
            "url": url,
            "published_at": datetime.now(UTC).isoformat(),
        })
        self._save_published_history(history)
        logger.info("Recorded in published history: '%s'", title[:60])

    def load_published_titles(self) -> set[str]:
        """Get set of all published titles (for dedup in topic selection)."""
        history = self._load_published_history()
        return {entry.get("title", "") for entry in history}

    def load_published_slugs(self) -> set[str]:
        """Get set of all published slugs."""
        history = self._load_published_history()
        return {entry.get("slug", "") for entry in history}

    @staticmethod
    def _hash_content(content: str) -> str:
        """Hash full content for dedup.

        Previously only hashed first 500 chars, which caused false positive dedup
        when two different articles shared a similar intro but diverged after.
        """
        normalized = content.strip().lower()
        return hashlib.sha256(normalized.encode()).hexdigest()[:16]

    @staticmethod
    def _slugify(title: str) -> str:
        """Convert title to URL-safe slug."""
        slug = title.lower().strip()
        slug = re.sub(r"[^\w\s-]", "", slug)
        slug = re.sub(r"[\s_]+", "-", slug)
        slug = re.sub(r"-+", "-", slug)
        return slug[:80].strip("-")
